Repository LikeLion-CAU-9th/Philo-coders, pull requests merged in 2021-06, with the labels that each got.

#10 [BE]- Feat: Profile model
  byurak/accounts/admin.py
  byurak/accounts/migrations/0002_auto_20210602_1538.py
  byurak/accounts/models.py
Labels: feature

#13 [BE]- feat: Group model class
  byurak/group/models.py
Labels: feature

#14 [FE]- Group page
  byurak/byurak/settings.py
  byurak/byurak/urls.py
  byurak/group/admin.py
  byurak/group/migrations/0001_initial.py
  byurak/group/migrations/0002_auto_20210603_1605.py
  byurak/group/models.py
  byurak/group/static/css/group_detail.css
  byurak/group/static/css/postit.css
  byurak/group/static/css/timeline.css
  byurak/group/static/image/calendarPictogram.png
  byurak/group/static/image/group_representive_image.png
  byurak/group/static/image/personPictogram.png
  byurak/group/templates/group_detail.html
  byurak/group/templates/group_list.html
  byurak/group/urls.py
  byurak/group/views.py
Labels: feature

#15 [BE]- feat: GroupNotice CRUD method
  byurak/group/admin.py
  byurak/group/forms.py
  byurak/group/migrations/0003_auto_20210604_1544.py
  byurak/group/migrations/0004_auto_20210604_1614.py
  byurak/group/migrations/0005_auto_20210604_1616.py
  byurak/group/migrations/0006_auto_20210605_1558.py
  byurak/group/models.py
  byurak/group/templates/group_detail.html
  byurak/group/urls.py
  byurak/group/views.py
Labels: feature

#17 [FE] - feat: feed ui
  byurak/byurak/templates/base.html
  byurak/feed/static/img/finding.png
  byurak/feed/static/img/just_looking.png
  byurak/feed/templates/feedhome.html
Labels: feature

#20 [BE] - Feat: DB scheme and view about accounts
  byurak/accounts/admin.py
  byurak/accounts/forms.py
  byurak/accounts/migrations/0003_auto_20210625_1651.py
  byurak/accounts/models.py
  byurak/accounts/templates/accounts_home.html
  byurak/accounts/templates/accounts_login.html
  byurak/accounts/templates/accounts_logout.html
  byurak/accounts/templates/accounts_signup.html
  byurak/accounts/templates/login_success.html
  byurak/accounts/templates/logout_success.html
  byurak/accounts/templates/signup_success.html
  byurak/accounts/urls.py
  byurak/accounts/views.py
  byurak/group/migrations/0007_alter_group_end_date.py
Labels: feature

#19 [FE] - Feat: signup UI
  byurak/accounts/static/css/new_main.css
  byurak/accounts/static/image/signup_stepper1.png
  byurak/accounts/static/image/signup_stepper2.png
  byurak/accounts/templates/signup_fin.html
  byurak/accounts/templates/signup_infor.html
  byurak/accounts/templates/signup_main.html
  byurak/accounts/urls.py
  byurak/accounts/views.py
Labels: feature

#21 [BE] - Feat: connect accounts's UI
  byurak/accounts/static/image/signup_stepper3.png
  byurak/accounts/templates/accounts_home.html
  byurak/accounts/templates/accounts_login.html
  byurak/accounts/templates/accounts_signup.html
  byurak/accounts/templates/signup_fin.html
  byurak/accounts/urls.py
  byurak/accounts/views.py
  byurak/byurak/templates/base.html
  byurak/group/migrations/0008_alter_group_end_date.py
Labels: feature

#22 [FE]- Feat: profile UI
  byurak/accounts/static/css/accounts.css
  byurak/accounts/static/image/profilePicture.jpg
  byurak/accounts/templates/index.html
  byurak/accounts/templates/profile-bookmark.html
  byurak/feed/static/img/search.png
Labels: feature

#18 [FE]- feat: feed_list ui
  byurak/byurak/templates/base.html
  byurak/feed/static/css/pinterest_effect.css
  byurak/feed/static/js/pinterest_effect.js
  byurak/feed/templates/feedhome.html
  byurak/feed/templates/post_home.html
  byurak/feed/urls.py
  byurak/feed/views.py
Labels: feature

#23 [BE] - feat: connect views
  byurak/accounts/urls.py
  byurak/byurak/templates/base.html
  byurak/feed/static/css/sliding.css
  byurak/feed/templates/landing.html
  byurak/feed/urls.py
Labels: feature

#25 [BE] - Feat: Profile
  byurak/accounts/migrations/0004_profile_user_type.py
  byurak/accounts/models.py
  byurak/accounts/views.py
Labels: feature

#26 [FE] - accounts/signup
  byurak/accounts/static/css/signup.css
  byurak/accounts/static/css/signup_main.css
  byurak/accounts/templates/accounts_signup.html
  byurak/accounts/templates/signup_fin.html
  byurak/accounts/templates/signup_infor.html
  byurak/accounts/templates/signup_main.html
  byurak/accounts/urls.py
  byurak/accounts/views.py
Labels: feature, fix

#28 [BE]- Feat: ProfileIntroduce class, Profile class
  byurak/accounts/migrations/0005_auto_20210628_1249.py
  byurak/accounts/models.py
Labels: feature

#29 [FE] - Fix/signup
  byurak/accounts/templates/accounts_login.html
  byurak/byurak/templates/base.html
Labels: fix

#32 [FE]- feat: linked service_provider to index.html
  byurak/accounts/forms.py
  byurak/accounts/migrations/0008_introduction.py
  byurak/accounts/models.py
  byurak/accounts/static/css/edit_intro.css
  byurak/accounts/templates/create_introduction.html
  byurak/accounts/templates/index.html
  byurak/accounts/templates/producerProfile.html
  byurak/accounts/urls.py
  byurak/accounts/views.py
  byurak/byurak/templates/base.html
  byurak/group/migrations/0009_alter_group_end_date.py
  byurak/group/migrations/0010_alter_group_end_date.py
Labels: feature

#30 [FE,BE] - Feature/map
  byurak/accounts/models.py
  byurak/mapsurfing/templates/surfingmap_depth1.html
  byurak/mapsurfing/views.py
Labels: feature

#33 [BE] feature/reservation
  byurak/byurak/settings.py
  byurak/byurak/urls.py
  byurak/reservation/__init__.py
  byurak/reservation/admin.py
  byurak/reservation/apps.py
  byurak/reservation/forms.py
  byurak/reservation/migrations/0001_initial.py
  byurak/reservation/migrations/__init__.py
  byurak/reservation/models.py
  byurak/reservation/templates/reservation_confirm.html
  byurak/reservation/templates/reservation_create.html
  byurak/reservation/templates/reservation_customer_confirm.html
  byurak/reservation/templates/reservation_host_confirm.html
  byurak/reservation/templates/reservation_pay_method.html
  byurak/reservation/templates/reservation_success.html
  byurak/reservation/tests.py
  byurak/reservation/urls.py
  byurak/reservation/views.py
Labels: feature

#35 [FE]- feat: completed index.html for default_user
  byurak/accounts/static/css/accounts.css
  byurak/accounts/static/image/bowandarrow.jpg
  byurak/accounts/static/image/chiljang.jpg
  byurak/accounts/static/image/haenyu-exp.png
  byurak/accounts/static/image/korean-traditional-dance.jpg
  byurak/accounts/static/image/line-walk.jpg
  byurak/accounts/static/image/mask.jpg
  byurak/accounts/static/image/myungju.jpg
  byurak/accounts/static/image/paragliding.jpeg
  byurak/accounts/static/image/surfy-beach.jpg
  byurak/accounts/templates/index.html
  byurak/byurak/templates/base.html
Labels: feature

#36 Feature/map
  byurak/byurak/templates/base.html
  byurak/mapsurfing/static/css/carousel.css
  byurak/mapsurfing/static/css/searchBar.css
  byurak/mapsurfing/static/js/carousel.js
  byurak/mapsurfing/templates/surfingmap_depth1.html
Labels: feature

#39 [FE]- refactor .css in base.html
  byurak/accounts/static/css/accounts.css
  byurak/accounts/static/image/god_yun_han.png
  byurak/byurak/templates/base.html
  byurak/feed/static/css/pinterest_effect.css
  byurak/feed/static/css/sliding.css
  byurak/feed/templates/feedhome.html
  byurak/feed/templates/landing.html
  byurak/feed/templates/landing2.html
  byurak/mapsurfing/static/css/searchBar.css
  byurak/mapsurfing/templates/surfingmap_depth1.html
  byurak/mapsurfing/templates/surfingmap_depth2.html
Labels: fix
